version: "3.3"

services:
    app-todo:

        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - './src:/app/src'

        ports:
            - '8080:8080'

        environment:
            - CHOKIDAR_USEPOLLING=true
